<h3>Happy Customers</h3>

<h4>Notebook 4</h4>

In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Bespoke functions
from model_evaluation import *
from data_prep import * 
from save_model import *

<h4>K-Nearest Neighbours</h4>

In [15]:
from sklearn.neighbors import KNeighborsClassifier

In [16]:
X,Y = generate_XY()
X_train_scaled, X_test_scaled, Y_train, Y_test = split_scale_data(X=X,Y=Y,stratify=Y["Y"],test_size=0.3)

knn = KNeighborsClassifier()
knn.fit(X_train_scaled, Y_train)

Y_pred = knn.predict(X_test_scaled)
Y_proba = knn.predict_proba(X_test_scaled)[:,1]

evaluate_binary_classifier(Y_test,Y_pred,Y_proba)


===== Binary Classification Evaluation =====

Accuracy: 0.5263
Balanced Accuracy: 0.5042
Precision: 0.5556
Recall: 0.7143
F1 Score: 0.6250
Matthews Corrcoef: 0.0092
ROC AUC: 0.5602
Log Loss: 3.4523

Confusion Matrix:
[[ 5 12]
 [ 6 15]]

Classification Report:
              precision    recall  f1-score   support

           0       0.45      0.29      0.36        17
           1       0.56      0.71      0.62        21

    accuracy                           0.53        38
   macro avg       0.51      0.50      0.49        38
weighted avg       0.51      0.53      0.51        38



{'metrics': {'Accuracy': 0.5263157894736842,
  'Balanced Accuracy': 0.5042016806722689,
  'Precision': 0.5555555555555556,
  'Recall': 0.7142857142857143,
  'F1 Score': 0.625,
  'Matthews Corrcoef': 0.009213166547046367,
  'ROC AUC': 0.5602240896358543,
  'Log Loss': 3.45234457690231},
 'confusion_matrix': array([[ 5, 12],
        [ 6, 15]]),
 'classification_report': '              precision    recall  f1-score   support\n\n           0       0.45      0.29      0.36        17\n           1       0.56      0.71      0.62        21\n\n    accuracy                           0.53        38\n   macro avg       0.51      0.50      0.49        38\nweighted avg       0.51      0.53      0.51        38\n'}

+Hyperparameter Tuning:

In [17]:
from sklearn.model_selection import GridSearchCV, StratifiedKFold

# Hyperparameter grid
param_grid = {
    "n_neighbors": [3, 5, 7, 9, 11, 15],
    "weights": ["uniform", "distance"],
    "metric": ["euclidean", "manhattan", "minkowski"],
    "p": [1, 2]
}

# CV strategy
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# Grid search
grid = GridSearchCV(
    estimator=KNeighborsClassifier(),
    param_grid=param_grid,
    scoring="f1_macro",
    cv=cv,
    n_jobs=-1,
    refit=True
)

grid.fit(X_train_scaled, Y_train)

print("Best params:", grid.best_params_)

# Evaluate tuned model on test set
best_knn = grid.best_estimator_
Y_pred_tuned = best_knn.predict(X_test_scaled)
Y_proba_tuned = best_knn.predict_proba(X_test_scaled)[:, 1]

evaluate_binary_classifier(Y_test, Y_pred_tuned, Y_proba_tuned)

Best params: {'metric': 'manhattan', 'n_neighbors': 11, 'p': 1, 'weights': 'distance'}

===== Binary Classification Evaluation =====

Accuracy: 0.6053
Balanced Accuracy: 0.5868
Precision: 0.6154
Recall: 0.7619
F1 Score: 0.6809
Matthews Corrcoef: 0.1858
ROC AUC: 0.6232
Log Loss: 4.3145

Confusion Matrix:
[[ 7 10]
 [ 5 16]]

Classification Report:
              precision    recall  f1-score   support

           0       0.58      0.41      0.48        17
           1       0.62      0.76      0.68        21

    accuracy                           0.61        38
   macro avg       0.60      0.59      0.58        38
weighted avg       0.60      0.61      0.59        38



{'metrics': {'Accuracy': 0.6052631578947368,
  'Balanced Accuracy': 0.5868347338935573,
  'Precision': 0.6153846153846154,
  'Recall': 0.7619047619047619,
  'F1 Score': 0.6808510638297872,
  'Matthews Corrcoef': 0.1857720118682934,
  'ROC AUC': 0.623249299719888,
  'Log Loss': 4.314485631141542},
 'confusion_matrix': array([[ 7, 10],
        [ 5, 16]]),
 'classification_report': '              precision    recall  f1-score   support\n\n           0       0.58      0.41      0.48        17\n           1       0.62      0.76      0.68        21\n\n    accuracy                           0.61        38\n   macro avg       0.60      0.59      0.58        38\nweighted avg       0.60      0.61      0.59        38\n'}

- Increase from 0.62 to 0.68 for tuned model.

+Smaller test split (0.15):

In [18]:
X,Y = generate_XY()
X_train_scaled, X_test_scaled, Y_train, Y_test = split_scale_data(X=X,Y=Y,stratify=Y["Y"],test_size=0.15)

# Hyperparameter grid
param_grid = {
    "n_neighbors": [3, 5, 7, 9, 11, 15],
    "weights": ["uniform", "distance"],
    "metric": ["euclidean", "manhattan", "minkowski"],
    "p": [1, 2]
}

# CV strategy
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# Grid search
grid_ssplit = GridSearchCV(
    estimator=KNeighborsClassifier(),
    param_grid=param_grid,
    scoring="f1_macro",
    cv=cv,
    n_jobs=-1,
    refit=True
)

grid_ssplit.fit(X_train_scaled, Y_train)

print("Best params:", grid_ssplit.best_params_)

# Evaluate tuned model on test set
best_knn_ssplit = grid_ssplit.best_estimator_
Y_pred_tuned = best_knn_ssplit.predict(X_test_scaled)
Y_proba_tuned = best_knn_ssplit.predict_proba(X_test_scaled)[:, 1]

evaluate_binary_classifier(Y_test, Y_pred_tuned, Y_proba_tuned)

Best params: {'metric': 'manhattan', 'n_neighbors': 9, 'p': 1, 'weights': 'distance'}

===== Binary Classification Evaluation =====

Accuracy: 0.5263
Balanced Accuracy: 0.5222
Precision: 0.5455
Recall: 0.6000
F1 Score: 0.5714
Matthews Corrcoef: 0.0449
ROC AUC: 0.6000
Log Loss: 4.2841

Confusion Matrix:
[[4 5]
 [4 6]]

Classification Report:
              precision    recall  f1-score   support

           0       0.50      0.44      0.47         9
           1       0.55      0.60      0.57        10

    accuracy                           0.53        19
   macro avg       0.52      0.52      0.52        19
weighted avg       0.52      0.53      0.52        19



{'metrics': {'Accuracy': 0.5263157894736842,
  'Balanced Accuracy': 0.5222222222222221,
  'Precision': 0.5454545454545454,
  'Recall': 0.6,
  'F1 Score': 0.5714285714285714,
  'Matthews Corrcoef': 0.044946657497549475,
  'ROC AUC': 0.6,
  'Log Loss': 4.2840731522493884},
 'confusion_matrix': array([[4, 5],
        [4, 6]]),
 'classification_report': '              precision    recall  f1-score   support\n\n           0       0.50      0.44      0.47         9\n           1       0.55      0.60      0.57        10\n\n    accuracy                           0.53        19\n   macro avg       0.52      0.52      0.52        19\nweighted avg       0.52      0.53      0.52        19\n'}

- It seems that a smaller test split reduces the F1-score.
- The best model for KNN is the hypertuned version.

<h4>Naive Bayes</h4>

- The correlation between features isn't particularly big (see notebook 1) so an algorithm like Naive Bayes could work well because it assumes features are conditionally independent given the class.

In [19]:
from sklearn.naive_bayes import GaussianNB #We are dealing with continuous numeric features not text or binary features so won't need MultinomialNB or BernoulliNB

X,Y = generate_XY()
X_train_scaled, X_test_scaled, Y_train, Y_test = split_scale_data(X=X,Y=Y,stratify=Y["Y"],test_size=0.3)

nb_model = GaussianNB()
nb_model.fit(X_train_scaled,Y_train)

Y_pred = nb_model.predict(X_test_scaled)
Y_proba = nb_model.predict_proba(X_test_scaled)[:, 1]

evaluate_binary_classifier(Y_test, Y_pred, Y_proba)


===== Binary Classification Evaluation =====

Accuracy: 0.5000
Balanced Accuracy: 0.4804
Precision: 0.5385
Recall: 0.6667
F1 Score: 0.5957
Matthews Corrcoef: -0.0419
ROC AUC: 0.6190
Log Loss: 0.7809

Confusion Matrix:
[[ 5 12]
 [ 7 14]]

Classification Report:
              precision    recall  f1-score   support

           0       0.42      0.29      0.34        17
           1       0.54      0.67      0.60        21

    accuracy                           0.50        38
   macro avg       0.48      0.48      0.47        38
weighted avg       0.48      0.50      0.48        38



{'metrics': {'Accuracy': 0.5,
  'Balanced Accuracy': 0.48039215686274506,
  'Precision': 0.5384615384615384,
  'Recall': 0.6666666666666666,
  'F1 Score': 0.5957446808510638,
  'Matthews Corrcoef': -0.04194851880896947,
  'ROC AUC': 0.6190476190476191,
  'Log Loss': 0.7808601563314624},
 'confusion_matrix': array([[ 5, 12],
        [ 7, 14]]),
 'classification_report': '              precision    recall  f1-score   support\n\n           0       0.42      0.29      0.34        17\n           1       0.54      0.67      0.60        21\n\n    accuracy                           0.50        38\n   macro avg       0.48      0.48      0.47        38\nweighted avg       0.48      0.50      0.48        38\n'}

- Base model has 0.59 F1-score.
- Hyperparameter tuning:

In [20]:
# Hyperparameter tuning for Gaussian Naive Bayes
param_grid_nb = {
    "var_smoothing": np.logspace(-12, -6, 25)
}

grid_nb = GridSearchCV(
    estimator=GaussianNB(),
    param_grid=param_grid_nb,
    scoring="f1_macro",
    cv=cv,
    n_jobs=-1,
    refit=True
)

grid_nb.fit(X_train_scaled, Y_train)

print("Best params:", grid_nb.best_params_)
print("Best CV f1_macro:", grid_nb.best_score_)

best_nb = grid_nb.best_estimator_
Y_pred_nb_tuned = best_nb.predict(X_test_scaled)
Y_proba_nb_tuned = best_nb.predict_proba(X_test_scaled)[:, 1]

evaluate_binary_classifier(Y_test, Y_pred_nb_tuned, Y_proba_nb_tuned)

Best params: {'var_smoothing': np.float64(1e-12)}
Best CV f1_macro: 0.48440407769045546

===== Binary Classification Evaluation =====

Accuracy: 0.5000
Balanced Accuracy: 0.4804
Precision: 0.5385
Recall: 0.6667
F1 Score: 0.5957
Matthews Corrcoef: -0.0419
ROC AUC: 0.6190
Log Loss: 0.7809

Confusion Matrix:
[[ 5 12]
 [ 7 14]]

Classification Report:
              precision    recall  f1-score   support

           0       0.42      0.29      0.34        17
           1       0.54      0.67      0.60        21

    accuracy                           0.50        38
   macro avg       0.48      0.48      0.47        38
weighted avg       0.48      0.50      0.48        38



{'metrics': {'Accuracy': 0.5,
  'Balanced Accuracy': 0.48039215686274506,
  'Precision': 0.5384615384615384,
  'Recall': 0.6666666666666666,
  'F1 Score': 0.5957446808510638,
  'Matthews Corrcoef': -0.04194851880896947,
  'ROC AUC': 0.6190476190476191,
  'Log Loss': 0.7808601571543333},
 'confusion_matrix': array([[ 5, 12],
        [ 7, 14]]),
 'classification_report': '              precision    recall  f1-score   support\n\n           0       0.42      0.29      0.34        17\n           1       0.54      0.67      0.60        21\n\n    accuracy                           0.50        38\n   macro avg       0.48      0.48      0.47        38\nweighted avg       0.48      0.50      0.48        38\n'}

- No difference.

+Feature selection

In [21]:
feature_cols = ['X1', 'X2', 'X4', 'X6']
X,Y = generate_XY(feature_cols=feature_cols)
X_train_scaled, X_test_scaled, Y_train, Y_test = split_scale_data(X=X,Y=Y,stratify=Y["Y"],test_size=0.3)

param_grid_nb = {
    "var_smoothing": np.logspace(-12, -6, 25)
}

grid_nb = GridSearchCV(
    estimator=GaussianNB(),
    param_grid=param_grid_nb,
    scoring="f1_macro",
    cv=cv,
    n_jobs=-1,
    refit=True
)

grid_nb.fit(X_train_scaled, Y_train)

print("Best params:", grid_nb.best_params_)
print("Best CV f1_macro:", grid_nb.best_score_)

best_nb = grid_nb.best_estimator_
Y_pred_nb_tuned = best_nb.predict(X_test_scaled)
Y_proba_nb_tuned = best_nb.predict_proba(X_test_scaled)[:, 1]

evaluate_binary_classifier(Y_test, Y_pred_nb_tuned, Y_proba_nb_tuned)

Best params: {'var_smoothing': np.float64(1e-12)}
Best CV f1_macro: 0.47256927036708973

===== Binary Classification Evaluation =====

Accuracy: 0.6053
Balanced Accuracy: 0.5980
Precision: 0.6364
Recall: 0.6667
F1 Score: 0.6512
Matthews Corrcoef: 0.1975
ROC AUC: 0.5560
Log Loss: 0.7396

Confusion Matrix:
[[ 9  8]
 [ 7 14]]

Classification Report:
              precision    recall  f1-score   support

           0       0.56      0.53      0.55        17
           1       0.64      0.67      0.65        21

    accuracy                           0.61        38
   macro avg       0.60      0.60      0.60        38
weighted avg       0.60      0.61      0.60        38



{'metrics': {'Accuracy': 0.6052631578947368,
  'Balanced Accuracy': 0.5980392156862745,
  'Precision': 0.6363636363636364,
  'Recall': 0.6666666666666666,
  'F1 Score': 0.6511627906976745,
  'Matthews Corrcoef': 0.1974661233610029,
  'ROC AUC': 0.5560224089635855,
  'Log Loss': 0.7396206796918051},
 'confusion_matrix': array([[ 9,  8],
        [ 7, 14]]),
 'classification_report': '              precision    recall  f1-score   support\n\n           0       0.56      0.53      0.55        17\n           1       0.64      0.67      0.65        21\n\n    accuracy                           0.61        38\n   macro avg       0.60      0.60      0.60        38\nweighted avg       0.60      0.61      0.60        38\n'}

- F1-score increased to 0.65 for feature selection

<h3>Best Model:

Based on all the models trained in these 4 notebooks and considering not just F1-score for the positive class but precision and recall of the negative class, the XGboost model with a 0.15 test split, hyperparameter tuned and with feature selection (features X3 and X5 dropped), is the strongest model with an F1-score of 0.69. We were able to get a higher F1-score with LR and SVM (0.71 each) but all the predictions made were for the positive class i.e. zero precision and recall for negative class predictions.

- Remaking the model and evaluating for repeatability, then saving it for re-use:

In [22]:
from xgboost import XGBClassifier

feature_cols = ['X1', 'X2', 'X4', 'X6']
X,Y = generate_XY(feature_cols=feature_cols)
X_train_scaled, X_test_scaled, Y_train, Y_test = split_scale_data(X=X,Y=Y,stratify=Y["Y"],test_size=0.15)

xgb_param_grid = {
    "n_estimators": [200, 300, 500, 1000],
    "learning_rate": [0.001, 0.005,0.01, 0.05, 0.1],
    "max_depth": [2, 3, 4, 5, 6, 7, 8, 9, 10],
    "subsample": [0.5, 0.6, 0.7, 0.8, 1.0],
    "colsample_bytree": [0.5, 0.6, 0.7, 0.8, 1.0]
}

xgb_grid = GridSearchCV(
    estimator=XGBClassifier(
        objective="binary:logistic",
        eval_metric="logloss",
        random_state=13
    ),
    param_grid=xgb_param_grid,
    cv=10,
    scoring="f1",
    n_jobs=-1
)

xgb_grid.fit(X_train_scaled, Y_train)

print("Best Params:", xgb_grid.best_params_)
print("Best CV F1:", xgb_grid.best_score_)

best_xgb = xgb_grid.best_estimator_
Y_xgb_grid_pred = best_xgb.predict(X_test_scaled)
Y_xgb_grid_proba = best_xgb.predict_proba(X_test_scaled)[:, 1]

xgb_grid_eval = evaluate_binary_classifier(Y_test, Y_xgb_grid_pred, Y_xgb_grid_proba)

Best Params: {'colsample_bytree': 1.0, 'learning_rate': 0.001, 'max_depth': 2, 'n_estimators': 200, 'subsample': 1.0}
Best CV F1: 0.755830639948287

===== Binary Classification Evaluation =====

Accuracy: 0.5789
Balanced Accuracy: 0.5611
Precision: 0.5625
Recall: 0.9000
F1 Score: 0.6923
Matthews Corrcoef: 0.1674
ROC AUC: 0.5944
Log Loss: 0.6830

Confusion Matrix:
[[2 7]
 [1 9]]

Classification Report:
              precision    recall  f1-score   support

           0       0.67      0.22      0.33         9
           1       0.56      0.90      0.69        10

    accuracy                           0.58        19
   macro avg       0.61      0.56      0.51        19
weighted avg       0.61      0.58      0.52        19



In [23]:
save_model(model=best_xgb,filename="xgb_classifier_",folder="models")